apiVersion: v1

# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: reddit-clone-service
spec:
  type: NodePort
  selector:
    # Selector for Pods
    app: reddit-clone
  ports:
    # Port Map
   - port: 3000
     targetPort: 3000
     NodePort: 30007

